Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/SoleNestedConditional:
  AllowModifier: true
